global: 
  marketplace-ami: false
  qsname: quickstart-heptio
  regions: 
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-2
  reporting: true
tests: 
  heptio: 
    parameter_input: quickstart-heptio.json
    template_file: quickstart-heptio-master.template
    regions: 
      - us-west-2
      - us-east-1
